version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/ruby:2.4.1-node
        environment:
          RAILS_ENV: test
      - image: docker pull circleci/mysql:5.6
        environment:
          MYSQL_USER: root
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_HOST: %
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: circleci_test
    steps:
      - checkout
      - restore_cache:
          key: rails-circleci-test-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: rails-circleci-test-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - run: bundle exec rspec
