version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: circleci/ruby:2.4.1-node
        environment:
          RAILS_ENV: test
    steps:
      - checkout
      - restore_cache:
          key: rails-circleci-test-{{ checksum "Gemfile.lock" }}
      - run:
          name: install dependencies
          command: bundle install --jobs=4 --path vendor/bundle
      - save_cache:
          key: rails-circleci-test-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
