default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: circleci_development

test:
  <<: *default
  database: circleci_test

production:
  <<: *default
  database: circleci_production
  username: rails-circleci
  password: <%= ENV['RAILS-CIRCLECI_DATABASE_PASSWORD'] %>
